        !COMPILER-GENERATED INTERFACE MODULE: Sat May 21 14:51:11 2016
        MODULE DO_LOOPS_WITH_CALLS__genmod
          INTERFACE 
            SUBROUTINE DO_LOOPS_WITH_CALLS
            END SUBROUTINE DO_LOOPS_WITH_CALLS
          END INTERFACE 
        END MODULE DO_LOOPS_WITH_CALLS__genmod
